import { Inter, Lato, Poppins } from "next/font/google";
import "../globals.css";
import "animate.css";
import ToasterProvider from "@/utils/ToasterProvider";
import { AppProvider } from "@/utils/AppContext";
import Sidebar from "@/components/admin/Sidebar";
import Header from "@/components/admin/Header";
import AdminMiddleware from "@/utils/adminMiddleware";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "SOLAR HUB NG",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AppProvider>
          <AdminMiddleware>
            <ToasterProvider />
            <div className="flex h-screen overflow-hidden">
              <Sidebar />
              <div className="relative flex flex-1 flex-col overflow-y-auto overflow">
                <Header />
                <div className="">{children}</div>
              </div>
            </div>
          </AdminMiddleware>
        </AppProvider>
      </body>
    </html>
  );
}
